// Copyright (c) 2024 The mgis Authors.
// All rights reserved.

#ifndef CONTENT_CONTROL_TOOL_COMMON_H
#define CONTENT_CONTROL_TOOL_COMMON_H

#include "content/common/message.h"

namespace content {
enum eMouseStatus {
  MS_NoStatus,
  MS_DLButtonDown,
  MS_LButtonDown,
  MS_LButtonUp,
  MS_MouseMove,
  MS_DRButtonDown,
  MS_RButtonDown,
  MS_RButtonUp,
  MS_MouseWeel
};

enum eFlashMode { FM_2 };
enum eViewMode {
  VM_ZoomOff,
  VM_ZoomIn,
  VM_ZoomOut,
  VM_ZoomMove,
  VM_ZoomRestore,
  VM_ZoomRefresh
};

enum eSelectMode { SM_Point, SM_Rect, SM_Circle, SM_Polygon };

enum e3DViewMode {
  VM_3DNormal,
  VM_3DTraceBall,
  VM_3DShpereCamera,
  VM_3DFirstPerson,
};

enum ePointType { PT_Dot, PT_Image, PT_Text };
enum eLineType {
  LT_Rect,
  LT_LineString,
  LT_LinearRing,
};

enum eSurfaceType { ST_Rect, ST_Polygon };
enum eEditType { ET_AppendFeature, ET_DeleteFeature, ET_ModifyFeature };
}  // namespace content

#define TOOL_MAX_MESSAGE_COUNT 20
#define TOOL_MAX_CMD_COUNT 30

// message
// 2d tool
#define TOOL_MESSAGE_DEFAULT_PROCESS (MESSAGE_2D_TOOL + 0)  // 默认处理
#define TOOL_MESSAGE_INVALID (MESSAGE_2D_TOOL + 1)  // 无效消息
#define TOOL_MESSAGE_RET_DELEGATE (MESSAGE_2D_TOOL + 2)  // 委托工具返回

// input point tool
#define TOOL_MESSAGE_BEGIN_INPUT_POINT \
  (MESSAGE_2D_TOOL + TOOL_MAX_MESSAGE_COUNT)  // 点输入工具开始消息
#define TOOL_MESSAGE_SET_INPUT_POINT_TYPE \
  (TOOL_MESSAGE_BEGIN_INPUT_POINT + 1)  // 设置输入点类型
#define TOOL_MESSAGE_GET_INPUT_POINT_TYPE \
  (TOOL_MESSAGE_BEGIN_INPUT_POINT + 2)  // 获取输入点类型
#define TOOL_MESSAGE_GET_INPUT_ANNO_ANGLE \
  (TOOL_MESSAGE_BEGIN_INPUT_POINT +       \
   3)  // 获取输入注记和角度(如果是输入注记的话)
#define TOOL_MESSAGE_RET_INPUT_POINT \
  (TOOL_MESSAGE_BEGIN_INPUT_POINT + 4)  // 返回输入点
#define TOOL_MESSAGE_END_INPUT_POINT \
  (TOOL_MESSAGE_BEGIN_INPUT_POINT +  \
   TOOL_MAX_MESSAGE_COUNT)  // 点输入工具结束消息

// input line tool
#define TOOL_MESSAGE_BEGIN_INPUT_LINE (TOOL_MESSAGE_END_INPUT_POINT + 1)
#define TOOL_MESSAGE_SET_INPUT_LINE_TYPE (TOOL_MESSAGE_BEGIN_INPUT_LINE + 1)
#define TOOL_MESSAGE_GET_INPUT_LINE_TYPE (TOOL_MESSAGE_BEGIN_INPUT_LINE + 2)
#define TOOL_MESSAGE_RET_INPUT_LINE (TOOL_MESSAGE_BEGIN_INPUT_LINE + 3)
#define TOOL_MESSAGE_END_INPUT_LINE \
  (TOOL_MESSAGE_BEGIN_INPUT_LINE + TOOL_MAX_MESSAGE_COUNT)

// input surface tool
#define TOOL_MESSAGE_BEGIN_INPUT_SURFACE (TOOL_MESSAGE_END_INPUT_LINE + 1)
#define TOOL_MESSAGE_SET_INPUT_SURFACE_TYPE \
  (TOOL_MESSAGE_BEGIN_INPUT_SURFACE + 1)
#define TOOL_MESSAGE_GET_INPUT_SURFACE_TYPE \
  (TOOL_MESSAGE_BEGIN_INPUT_SURFACE + 2)
#define TOOL_MESSAGE_RET_INPUT_SURFACE (TOOL_MESSAGE_BEGIN_INPUT_SURFACE + 3)
#define TOOL_MESSAGE_END_INPUT_SURFACE \
  (TOOL_MESSAGE_BEGIN_INPUT_SURFACE + TOOL_MAX_MESSAGE_COUNT)

// flash tool
#define TOOL_MESSAGE_BEGIN_FLASH (TOOL_MESSAGE_END_INPUT_SURFACE + 1)
#define TOOL_MESSAGE_SET_FLASH_MODE (TOOL_MESSAGE_BEGIN_FLASH + 1)
#define TOOL_MESSAGE_GET_FLASH_MODE (TOOL_MESSAGE_BEGIN_FLASH + 2)
#define TOOL_MESSAGE_SET_FLASH_PARAMETERS (TOOL_MESSAGE_BEGIN_FLASH + 3)
#define TOOL_MESSAGE_SET_FLASH_DATA (TOOL_MESSAGE_BEGIN_FLASH + 4)
#define TOOL_MESSAGE_GET_STATUS (TOOL_MESSAGE_BEGIN_FLASH + 5)
#define TOOL_MESSAGE_END_FLASH \
  (TOOL_MESSAGE_BEGIN_FLASH + TOOL_MAX_MESSAGE_COUNT)

// select tool
#define TOOL_MESSAGE_BEGIN_SELECT (TOOL_MESSAGE_END_FLASH + 1)
#define TOOL_MESSAGE_SET_SEL_MODE (TOOL_MESSAGE_BEGIN_SELECT + 1)
#define TOOL_MESSAGE_GET_SEL_MODE (TOOL_MESSAGE_BEGIN_SELECT + 2)
#define TOOL_MESSAGE_END_SELECT \
  (TOOL_MESSAGE_BEGIN_SELECT + TOOL_MAX_MESSAGE_COUNT)

// navigate tool
#define TOOL_MESSAGE_BEGIN_NAVIGATE (TOOL_MESSAGE_END_SELECT + 1)
#define TOOL_MESSAGE_GET_VIEW_MODE (TOOL_MESSAGE_BEGIN_NAVIGATE + 1)
#define TOOL_MESSAGE_SET_VIEW_MODE (TOOL_MESSAGE_BEGIN_NAVIGATE + 2)
#define TOOL_MESSAGE_SET_SCALEDELT (TOOL_MESSAGE_BEGIN_NAVIGATE + 3)
#define TOOL_MESSAGE_GET_SCALEDELT (TOOL_MESSAGE_BEGIN_NAVIGATE + 4)
#define TOOL_MESSAGE_END_NAVIGATE (TOOL_MESSAGE_BEGIN_NAVIGATE + 10)

//////////////////////////////////////////////////////////////////////////
// navigate control tool
#define TOOL_MESSAGE_CMD_NAVIGATE_BEGIN MESSAGE_CMD_BEGIN
#define TOOL_MESSAGE_VIEW_ZOOMIN (TOOL_MESSAGE_CMD_NAVIGATE_BEGIN + 1)
#define TOOL_MESSAGE_VIEW_ZOOMOUT (TOOL_MESSAGE_CMD_NAVIGATE_BEGIN + 2)
#define TOOL_MESSAGE_VIEW_ZOOMMOVE (TOOL_MESSAGE_CMD_NAVIGATE_BEGIN + 3)
#define TOOL_MESSAGE_VIEW_ZOOMRESTORE (TOOL_MESSAGE_CMD_NAVIGATE_BEGIN + 4)
#define TOOL_MESSAGE_VIEW_ZOOMREFRESH (TOOL_MESSAGE_CMD_NAVIGATE_BEGIN + 5)
#define TOOL_MESSAGE_VIEW_ACTIVE (TOOL_MESSAGE_CMD_NAVIGATE_BEGIN + 6)
#define TOOL_MESSAGE_CMD_NAVIGATE_END \
  (TOOL_MESSAGE_CMD_NAVIGATE_BEGIN + TOOL_MAX_MESSAGE_COUNT)

// select tool
#define TOOL_MESSAGE_CMD_SELECT_BEGIN (TOOL_MESSAGE_END_NAVIGATE + 1)
#define TOOL_MESSAGE_SELECT_POINTSEL (TOOL_MESSAGE_CMD_SELECT_BEGIN + 1)
#define TOOL_MESSAGE_SELECT_RECTSEL (TOOL_MESSAGE_CMD_SELECT_BEGIN + 2)
#define TOOL_MESSAGE_SELECT_POLYGONSEL (TOOL_MESSAGE_CMD_SELECT_BEGIN + 3)
#define TOOL_MESSAGE_SELECT_CLEAR (TOOL_MESSAGE_CMD_SELECT_BEGIN + 4)
#define TOOL_MESSAGE_CMD_SELECT_END \
  (TOOL_MESSAGE_CMD_SELECT_BEGIN + TOOL_MAX_MESSAGE_COUNT)

// flash tool
#define TOOL_MESSAGE_CMD_FLASH_BEGIN (TOOL_MESSAGE_CMD_SELECT_END + 1)
#define TOOL_MESSAGE_START_FLASH (TOOL_MESSAGE_CMD_FLASH_BEGIN + 1)
#define TOOL_MESSAGE_STOP_FLASH (TOOL_MESSAGE_CMD_FLASH_BEGIN + 2)
#define TOOL_MESSAGE_CMD_FLASH_END \
  (TOOL_MESSAGE_CMD_FLASH_BEGIN + TOOL_MAX_MESSAGE_COUNT)

// append feature tool
#define TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN (TOOL_MESSAGE_CMD_FLASH_END + 1)
// point feature
#define TOOL_MESSAGE_APPEND_POINT_CHILDIMAGE_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 1)
#define TOOL_MESSAGE_APPEND_POINT_ANNO_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 2)
#define TOOL_MESSAGE_APPEND_POINT_DOT_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 3)

// line feature
#define TOOL_MESSAGE_APPEND_LINE_SPLINE_LAG_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 4)
#define TOOL_MESSAGE_APPEND_LINE_SPLINE_BZER_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 5)
#define TOOL_MESSAGE_APPEND_LINE_SPLINE_B_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 6)
#define TOOL_MESSAGE_APPEND_LINE_SPLINE_3_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 7)
#define TOOL_MESSAGE_APPEND_LINE_LINESMRING_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 8)
#define TOOL_MESSAGE_APPEND_LINE_RECT_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 9)
#define TOOL_MESSAGE_APPEND_LINE_ARC_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 10)
#define TOOL_MESSAGE_APPEND_LINE_LINEARRING_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 11)

// surface feature
#define TOOL_MESSAGE_APPEND_SURFACE_FAN_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 12)
#define TOOL_MESSAGE_APPEND_SURFACE_RECT_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 13)
#define TOOL_MESSAGE_APPEND_SURFACE_POLYGON_FEATURE \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + 14)
#define TOOL_MESSAGE_CMD_APPEND_FEATURE_END \
  (TOOL_MESSAGE_CMD_APPEND_FEATURE_BEGIN + TOOL_MAX_CMD_COUNT)

#endif  // CONTENT_CONTROL_TOOL_COMMON_H