# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

template("benchmark") {
  executable(target_name) {
    forward_variables_from(invoker, "*")

    testonly = true

    sources += [
      "//testing/benchmark_main.cpp",
    ]

    include_dirs += [
      "$root_gen_dir/",
    ]

    deps += [
      "//third_party:gbenchmark",
    ]
  }
}
