# Copyright (c) 2023 The Mogu Authors.
# All rights reserved.

template("test") {
  executable(target_name) {
    forward_variables_from(invoker, "*")

    testonly = true

    sources += [
      "//testing/main.cpp",
    ]

    include_dirs += [
      "$root_gen_dir/",
    ]

    deps += [
      "//base:base",
      "//third_party:glog",
      "//third_party:gbenchmark",
      "//third_party:gtest",
    ]
  }
}
