# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.

import("//testing/test.gni")

group("gfx_3d_all") {
  deps = [
    ":renderer3d",
    ":render_device_d3d",
  ]
}

static_library("renderer3d") {
  defines = [
    "NOMINMAX",
  ]

  sources = [
    "renderer/renderer.cpp",
  ]

  include_dirs += [
    "$root_gen_dir/",
  ]

  libs = [
  ]

  deps = [
    "//base:base",
  ]
}

shared_library("render_device_d3d") {
  defines = [
    "NOMINMAX",
    "COMPONENT_BUILD",
    "GFX_3D_RENDER_DEVICE_IMPLEMENTATION",
  ]

  sources = [
    "render_device_d3d/export.cpp",
    "render_device_d3d/render_device_d3d.cpp",
  ]

  include_dirs += [
    "$root_gen_dir/",
  ]

  deps = [
    "//base:base",
    ":renderer3d",
    "//third_party:glog",
  ]
}

test("renderer3d_test") {
  defines = [
    "NOMINMAX",
  ]

  sources = [
    "render3d_unittest.cpp",
  ]

  include_dirs += [
    "$root_gen_dir/",
  ]

  libs = [
  ]

  deps = [
    ":renderer3d",
  ]
}