# Copyright (c) 2026 The Mogu Authors.
# All rights reserved.
import("//testing/test.gni")

group("gfx_2d_all") {
  deps = [
    ":renderer2d",
    ":render_device_gdi",
  ]
}

static_library("renderer2d") {
  defines = [
    "NOMINMAX",
  ]

  sources = [
    "renderer/renderer.cpp",
    "renderer/style.cpp",
  ]

  include_dirs += [
    "$root_gen_dir/",
  ]

  deps = [
    "//base:base",
    "//third_party:glog",
    "//third_party:gdal",
  ]
}

shared_library("render_device_gdi") {
  defines = [
    "NOMINMAX",
    "COMPONENT_BUILD",
    "GFX_2D_RENDER_DEVICE_IMPLEMENTATION",
  ]

  sources = [
    "render_device_gdi/export.cpp",
    "render_device_gdi/render_buffer.cpp",
    "render_device_gdi/render_device_gdi.cpp",
    "render_device_gdi/utils.cpp",
  ]

  include_dirs += [
    "$root_gen_dir/",
  ]

  deps = [
    "//base:base",
    ":renderer2d",
    "//third_party/CxImage:CxImage",
    "//third_party:glog",
    "//third_party:gdal",
  ]
}

test("renderer2d_test") {
  defines = [
    "NOMINMAX",
  ]

  sources = [
    "render2d_unittest.cpp",
  ]

  include_dirs += [
    "$root_gen_dir/",
  ]

  deps = [
    "//third_party:glog",
    "//third_party:gdal",
    ":renderer2d",
  ]
}